/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/earth.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Earth.geometry} material={materials['Earth Material']} scale={[10, 10, 10]} />
      <mesh
        name="Clouds"
        geometry={nodes.Clouds.geometry}
        material={materials['Clouds Material']}
        scale={[10.06, 10.06, 10.06]}
      />
    </group>
  )
}

useGLTF.preload('/earth.glb')
