/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/GEO-2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0.05, -0.01, -0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.025']}
        position={[0.05, -0.61, -0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.010']}
        position={[2.25, -0.06, -1.04]}
        rotation={[-0.26, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Material.022']}
        position={[0.07, -1.46, 1.75]}
        rotation={[-0.65, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials['Material.023']}
        position={[1.26, -1.19, -1.83]}
        rotation={[0.97, -0.25, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials['Material.024']}
        position={[-1.07, -1.22, -1.84]}
        rotation={[0.96, 0.36, -0.46]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.021']}
        position={[0.01, 0.2, -0.17]}
        rotation={[-1.53, 0, -1.57]}
        scale={[-0.1, 9.34, -0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[1.19, -1.51, -1.67]}
        rotation={[1.42, -0.16, 0.43]}
        scale={[-0.01, 0.84, -0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.013']}
        position={[4.34, -0.06, -1.04]}
        rotation={[-0.26, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.014']}
        position={[6.41, -0.06, -1.04]}
        rotation={[-0.26, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.015']}
        position={[8.49, -0.06, -1.04]}
        rotation={[-0.26, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.019']}
        position={[-6.3, -0.06, -1.1]}
        rotation={[-0.26, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.018']}
        position={[-4.22, -0.06, -1.1]}
        rotation={[-0.26, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Material.017']}
        position={[-2.15, -0.06, -1.1]}
        rotation={[-0.26, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Material.016']}
        position={[-8.39, -0.06, -1.1]}
        rotation={[-0.26, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-1.14, -1.54, -1.76]}
        rotation={[-1.42, -0.08, 0.46]}
        scale={[-0.01, 0.84, -0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[0.09, -1.76, 1.58]}
        rotation={[-1.1, -0.28, 0.2]}
        scale={[-0.01, 0.84, -0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[-1.02, 0.88, -1.14]}
        rotation={[1.04, 0.39, -0.58]}
        scale={[0.05, 0.17, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[1.09, 0.85, -1.14]}
        rotation={[0.97, -0.25, 0.35]}
        scale={[0.05, 0.17, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[1.12, 0.86, 1.05]}
        rotation={[2.11, -0.37, 2.6]}
        scale={[0.05, 0.17, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere006.geometry}
        material={nodes.Sphere006.material}
        position={[-1.02, 0.85, 1.05]}
        rotation={[2.08, 0.42, -2.51]}
        scale={[0.05, 0.17, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={materials['Material.027']}
        position={[0.03, 0.99, -0.02]}
        scale={[0.59, 0.24, 0.59]}
      />
    </group>
  )
}

useGLTF.preload('/GEO-2.glb')
