/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Turksat-6A.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.54, 1.73, 0.38]} rotation={[-Math.PI / 2, -1.22, -Math.PI / 2]} scale={[0.34, 0.45, 0.09]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={materials['Black Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube007_2.geometry} material={materials['White Material.001']} />
      </group>
      <group position={[-0.39, -1.7, 0.38]} rotation={[Math.PI / 2, -1.13, -Math.PI / 2]} scale={[0.32, 0.43, 0.09]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube010_1.geometry} material={materials['Black Material.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube010_2.geometry} material={materials['White Material.002']} />
      </group>
      <group position={[1.1, -0.5, -0.54]} rotation={[-Math.PI, -1.04, -Math.PI / 2]} scale={[0.24, 0.32, 0.06]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube011_1.geometry} material={materials['Black Material.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube011_2.geometry} material={materials['White Material.003']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.004']}
        position={[1.86, -0.46, 0.27]}
        rotation={[-1.56, 0, -0.41]}
        scale={[0.14, 0.28, 0.14]}
      />
      <group position={[1.88, -0.44, 0.19]} rotation={[-0.08, 0.96, -1.42]} scale={[0.07, 0.09, 0.02]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials['Black Material.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_2.geometry} material={materials['White Material.004']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.001']}
        position={[1.86, 0.58, 0.28]}
        rotation={[0.74, 0, -0.41]}
        scale={[0.14, 0.28, 0.14]}
      />
      <group position={[1.88, 0.63, 0.48]} rotation={[2, 1.32, -1.14]} scale={[0.07, 0.09, 0.02]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube014_1.geometry} material={materials['Black Material.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube014_2.geometry} material={materials['White Material.005']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Material.002']}
        position={[1.86, 0.57, 0.03]}
        rotation={[-0.79, 0, -0.41]}
        scale={[0.14, 0.28, 0.14]}
      />
      <group position={[1.88, 0.64, 0.11]} rotation={[0.5, 1.35, -1.31]} scale={[0.07, 0.09, 0.02]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials['Black Material.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_2.geometry} material={materials['White Material.006']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster1.geometry}
        material={materials['Gray Metal']}
        position={[1.08, 0.8, 0.5]}
        rotation={[Math.PI / 2, 0, -1.58]}
        scale={[0.02, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster1001.geometry}
        material={materials['Gray Metal']}
        position={[1.08, 0.78, 0.09]}
        rotation={[Math.PI / 2, 0, -1.58]}
        scale={[0.02, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2.geometry}
        material={materials['Gray Metal']}
        position={[1.03, 0.91, 0.68]}
        rotation={[-0.32, -1.14, -1.08]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2001.geometry}
        material={materials['Gray Metal']}
        position={[1.03, 0.91, -0.67]}
        rotation={[-1.41, -1.14, -1.08]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2002.geometry}
        material={materials['Gray Metal']}
        position={[1.03, 0.09, 0.7]}
        rotation={[1.14, -1.27, -0.61]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster3.geometry}
        material={materials['Gray Metal']}
        position={[1.02, 0.43, 0.65]}
        rotation={[-0.97, 0.16, -0.11]}
        scale={[0.03, 0.03, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster3001.geometry}
        material={materials['Gray Metal']}
        position={[1.02, 0.43, -0.58]}
        rotation={[-2.93, 0.16, -0.11]}
        scale={[0.03, 0.03, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster3002.geometry}
        material={materials['Gray Metal']}
        position={[1.02, 0.29, -0.58]}
        rotation={[-2.93, 0.16, -0.11]}
        scale={[0.03, 0.03, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster3003.geometry}
        material={materials['Gray Metal']}
        position={[1.02, -0.17, 0.61]}
        rotation={[0.02, 0.35, -0.11]}
        scale={[0.03, 0.03, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster3004.geometry}
        material={materials['Gray Metal']}
        position={[1.02, -0.27, 0.61]}
        rotation={[0.02, 0.35, -0.11]}
        scale={[0.03, 0.03, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2003.geometry}
        material={materials['Gray Metal']}
        position={[1.03, -0.9, 0.7]}
        rotation={[1.64, -1.27, -0.61]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2004.geometry}
        material={materials['Gray Metal']}
        position={[1.03, -0.9, -0.68]}
        rotation={[2.95, -1.27, -0.61]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2005.geometry}
        material={materials['Gray Metal']}
        position={[1.03, -0.9, 0.41]}
        rotation={[2.77, -1.27, -0.61]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2006.geometry}
        material={materials['Gray Metal']}
        position={[1.03, -0.9, 0.27]}
        rotation={[2.45, -1.27, -0.61]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster1002.geometry}
        material={materials['Gray Metal']}
        position={[1.24, -0.44, 0.08]}
        rotation={[Math.PI / 2, 0, -1.58]}
        scale={[0.02, 0.04, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2007.geometry}
        material={materials['Gray Metal']}
        position={[1.03, -0.22, -0.68]}
        rotation={[-2.25, -1.27, -0.61]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials.Material}
        position={[0.34, 0.91, 0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['Material.003']}
        position={[0.28, 0.91, 0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials['Material.005']}
        position={[0.21, 0.91, 0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004.geometry}
        material={materials['Material.006']}
        position={[0.15, 0.91, 0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={materials['Material.007']}
        position={[0.09, 0.91, 0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={materials['Material.008']}
        position={[0.02, 0.91, 0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle012.geometry}
        material={materials['Material.014']}
        position={[0.28, 0.91, -0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle011.geometry}
        material={materials['Material.013']}
        position={[0.21, 0.91, -0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle010.geometry}
        material={materials['Material.012']}
        position={[0.34, 0.91, -0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle009.geometry}
        material={materials['Material.011']}
        position={[0.15, 0.91, -0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008.geometry}
        material={materials['Material.010']}
        position={[0.09, 0.91, -0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={materials['Material.009']}
        position={[0.02, 0.91, -0.57]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2008.geometry}
        material={materials['Gray Metal']}
        position={[-1.02, 0.94, -0.7]}
        rotation={[-0.48, 0.46, 0.55]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2009.geometry}
        material={materials['Gray Metal']}
        position={[-1.02, 0.94, 0.71]}
        rotation={[-2.39, 0.92, 2.82]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2010.geometry}
        material={materials['Gray Metal']}
        position={[-1.02, -0.92, -0.72]}
        rotation={[-2.61, 0.73, 0.37]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2011.geometry}
        material={materials['Gray Metal']}
        position={[-1, -0.92, 0.71]}
        rotation={[2.54, 0.87, 0.21]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2012.geometry}
        material={materials['Gray Metal']}
        position={[-1.03, -0.06, 0.75]}
        rotation={[0.03, 1.01, 1.29]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2013.geometry}
        material={materials['Gray Metal']}
        position={[-0.97, -0.1, -0.74]}
        rotation={[0.96, 1, -2.7]}
        scale={[0.02, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2014.geometry}
        material={materials['Gray Metal']}
        position={[-1.04, 0.59, 0.26]}
        rotation={[-0.73, 0.91, 0.94]}
        scale={[0.02, 0.02, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster2015.geometry}
        material={materials['Gray Metal']}
        position={[-1.04, 0.59, 0.4]}
        rotation={[-0.42, 0.91, 0.94]}
        scale={[0.02, 0.02, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle016.geometry}
        material={materials['Material.018']}
        position={[0.21, -0.9, 0.57]}
        rotation={[-3.12, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle015.geometry}
        material={materials['Material.017']}
        position={[0.15, -0.9, 0.57]}
        rotation={[-3.12, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle014.geometry}
        material={materials['Material.016']}
        position={[0.09, -0.9, 0.57]}
        rotation={[-3.12, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle013.geometry}
        material={materials['Material.015']}
        position={[0.02, -0.9, 0.57]}
        rotation={[-3.12, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle020.geometry}
        material={materials['Material.022']}
        position={[0.02, -0.9, -0.59]}
        rotation={[-3.12, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle019.geometry}
        material={materials['Material.021']}
        position={[0.09, -0.9, -0.59]}
        rotation={[-3.12, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle018.geometry}
        material={materials['Material.020']}
        position={[0.15, -0.9, -0.59]}
        rotation={[-3.12, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle017.geometry}
        material={materials['Material.019']}
        position={[0.21, -0.9, -0.59]}
        rotation={[-3.12, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thruster1003.geometry}
        material={materials['Gray Metal']}
        position={[0.3, -0.93, 0.31]}
        rotation={[-Math.PI / 2, -0.37, 1.56]}
        scale={[0.02, 0.04, 0.02]}
      />
      <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials['Black Material']} />
      <group name="Wing1" position={[0, 0, 2.91]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials['Solar Panel Material.003']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_2.geometry} material={materials['Black Material']} />
      </group>
      <group position={[0, 0, -2.9]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials['Solar Panel Material.004']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Cube008_2.geometry} material={materials['Black Material']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Grid Material']}
        position={[-0.61, 0.38, 0.71]}
        scale={[0.35, 0.44, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['Grid Material']}
        position={[0.37, 0.47, 0.71]}
        scale={[0.58, 0.34, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials['Grid Material']}
        position={[0.56, -0.41, 0.71]}
        scale={[0.38, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials['Grid Material']}
        position={[-0.44, -0.47, 0.71]}
        scale={[0.25, 0.35, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials['Grid Material']}
        position={[-0.8, -0.47, 0.71]}
        scale={[0.07, 0.35, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials['Grid Material']}
        position={[-0.61, 0.38, -0.7]}
        scale={[0.35, 0.44, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials['Grid Material']}
        position={[0.37, 0.47, -0.7]}
        scale={[0.58, 0.34, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials['Grid Material']}
        position={[0.56, -0.41, -0.7]}
        scale={[0.38, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials['Grid Material']}
        position={[-0.44, -0.47, -0.7]}
        scale={[0.25, 0.35, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['Grid Material']}
        position={[-0.8, -0.47, -0.7]}
        scale={[0.07, 0.35, 0]}
      />
      <group position={[-1.11, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.06, 0.12, 0.06]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials['Frame Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials['Inner Foil Material.002']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Turksat-6A.glb')
